# Generated by Django 4.1.7 on 2023-06-13 11:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='station_avatar',
            field=models.ImageField(default='accounts/images/default_station_photo.jpeg',
                                    null=True, upload_to=accounts.models.station_avatar),
        ),
    ]
