# Generated by Django 4.1.7 on 2023-06-15 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_servicestation_station_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='EDRPOU',
            field=models.IntegerField(default=None, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
    ]
