# Generated by Django 4.1.7 on 2023-04-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicestation_user_service_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_station',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.servicestation'),
        ),
    ]
