# Generated by Django 4.1.7 on 2023-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_edrpou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='EDRPOU',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
