# Generated by Django 4.1.7 on 2023-04-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_service_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service_station',
        ),
        migrations.AddField(
            model_name='servicestation',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.servicestation'),
        ),
        migrations.AddField(
            model_name='user',
            name='EDRPOU',
            field=models.IntegerField(default=None, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
