# Generated by Django 4.1.7 on 2023-05-04 15:03

import autohistory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=autohistory.models.photo_damages)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=20)),
                ('mileage_units', models.CharField(choices=[('Км', 'Кілометр'), ('Мі', 'Мілі')], max_length=2)),
                ('mileage', models.IntegerField()),
                ('mileage_photo', models.ImageField(null=True, upload_to=autohistory.models.photo_mileage)),
                ('damage', models.TextField(max_length=1000)),
                ('work', models.TextField(max_length=10000)),
                ('check_number', models.CharField(max_length=22)),
                ('created', models.DateField(auto_now_add=True)),
                ('damage_photo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autohistory.damagephoto')),
                ('service_station_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.servicestation')),
            ],
        ),
    ]
