# Generated by Django 4.1.7 on 2023-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=20)),
                ('mileage_units', models.CharField(choices=[('Км', 'Кілометр'), ('Мі', 'Мілі')], max_length=2)),
                ('mileage', models.CharField(max_length=7)),
                ('service_station_name', models.CharField(max_length=80)),
                ('damage', models.TextField(max_length=1000)),
                ('work', models.TextField(max_length=10000)),
                ('check_number', models.CharField(max_length=22)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
