# Generated by Django 4.1.7 on 2023-05-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='damage_photo',
        ),
        migrations.AddField(
            model_name='damagephoto',
            name='car_story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='damage_photos', to='autohistory.car'),
            preserve_default=False,
        ),
    ]
