# Generated by Django 4.1.7 on 2023-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(max_length=7),
        ),
    ]
