# Generated by Django 4.1.7 on 2023-05-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0002_remove_car_damage_photo_damagephoto_car_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagephoto',
            name='car_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autohistory.car'),
        ),
    ]
