# Generated by Django 4.1.7 on 2023-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_servicestation_station_avatar'),
        ('comments_and_rating', '0002_alter_servicestationrating_rating'),
        ('autohistory', '0003_alter_damagephoto_car_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='CarStory',
        ),
    ]
