# Generated by Django 4.1.7 on 2023-04-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_servicestation_company'),
        ('autohistory', '0003_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='service_station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.servicestation'),
        ),
    ]
