# Generated by Django 4.1.7 on 2023-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0004_rename_car_carstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstory',
            name='vin_code',
            field=models.CharField(max_length=17),
        ),
    ]
