# Generated by Django 4.1.7 on 2023-04-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autohistory', '0004_alter_car_service_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsAndRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('car_working', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='autohistory.car')),
            ],
        ),
    ]
