# Generated by Django 4.1.7 on 2023-05-04 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('autohistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5)),
                ('service_station', models.OneToOneField(on_delete=django.db.models.fields.DateField, to='accounts.servicestation')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsAndRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('car_working', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autohistory.car')),
            ],
        ),
    ]
