# Generated by Django 4.1.7 on 2023-04-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0004_alter_car_service_station_name'),
        ('comments_and_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsandratings',
            name='car_working',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autohistory.car'),
        ),
    ]
