# Generated by Django 4.1.7 on 2023-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestationrating',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
