# Generated by Django 4.1.7 on 2023-04-26 12:49

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_servicestation_company'),
        ('comments_and_rating', '0003_alter_commentsandratings_car_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5)),
                ('service_station', models.OneToOneField(on_delete=django.db.models.fields.DateField, to='accounts.servicestation')),
            ],
        ),
    ]
